import sys
import generation
import validation

"""
        Assembly Testing Program

This is the main file of the ATP. 
ATP is a tool made for validating EVE assembly code output.

Until now, this tool can:
    - Get and save assembly code from functions listed in config.json
    - Validate instructions generated by the current version of EVE by comparing 
    them with instructions previously saved in functions.json

Calling asmTesting without any option starts the validation process.
Options are:
    - `-g` : Generate functions assembly. Functions that are not stored in functions.json are append.
    - `-d` : Deep update -- Functions are replaced in functions.json even though they were already in.
    - `-t` : Keep temporary files after processing
"""


if __name__ == '__main__':
    argv = sys.argv
    if '-g' in argv:
        deep = '-d' in argv
        tmp = '-t' in argv
        generation.update(deep=deep, keep_tmp=tmp)
    else:
        validation.validate()
